import {useEffect,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {ArrowRight,CalendarDays,Check,Clock3,MapPin,Menu,Phone,Ticket,X} from 'lucide-react';
const S='https://hpgujfzzallqfhiufuhn.supabase.co',LOGO=S+'/storage/v1/object/public/dennob%20b%20photos/WhatsApp%20Image%202026-10-07%20at%209.41.16%20PM.jpeg',PHOTO=S+'/storage/v1/object/public/dennob%20b%20photos/WhatsApp%20Image%202026-10-07%20at%201.19.58%20PM.jpeg';
const types=[['regular','0223b743-9fef-47c4-a72b-2ca5ca7c4906','Regular',500],['vip','664fc617-7a9a-49f5-84e8-986ccd3ca02f','VIP',1500],['vvip','10beb201-03c6-4686-a43e-d3ec59a432ff','VVIP',2000]] as const;
type T={ticket_number:string;qr_token:string;issued_at:string}; type B={ticketName:string;price:number;quantity:number;name:string;email:string;tickets:T[]};
const wa=(n:string)=>'https://wa.me/254'+n.slice(1);

function App(){const[page,setPage]=useState(location.hash.slice(1)||'home'),[open,setOpen]=useState<typeof types[number]|null>(null),[menu,setMenu]=useState(false),[f,setF]=useState({name:'',phone:'',email:''}),[qty,setQty]=useState(1),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[cancel,setCancel]=useState(false),[booking,setBooking]=useState<B|null>(()=>{try{return JSON.parse(localStorage.getItem('denno-b-studio-ticket')||'null')}catch{return null}});useEffect(()=>{const h=()=>{setPage(location.hash.slice(1)||'home');setMenu(false);scrollTo(0,0)};addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);
async function pay(){if(!open||busy)return;const e=!f.name.trim()||!/^[0-9+ ]{9,15}$/.test(f.phone)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email);if(e){setErr('Please enter a valid name, Kenyan phone number and email.');return}setBusy(true);setErr('');try{const r=await fetch(S+'/functions/v1/create-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticket_type_id:open[1],customer_name:f.name,customer_phone:f.phone,customer_email:f.email,quantity:qty})});const x=await r.json();if(!r.ok||!x.success)throw Error(x.error||'Payment could not start.');const end=Date.now()+120000;while(Date.now()<end){await new Promise(r=>setTimeout(r,3000));const q=await fetch(S+'/functions/v1/payment-status?external_reference='+encodeURIComponent(x.external_reference));const st=await q.json();if(st.status==='paid'&&st.tickets?.length){const b={ticketName:open[2],price:open[3],quantity:Number(st.quantity)||qty,name:st.customer_name||f.name,email:st.customer_email||f.email,tickets:st.tickets};localStorage.setItem('denno-b-studio-ticket',JSON.stringify(b));setBooking(b);setOpen(null);location.hash='ticket';return}if(['cancelled','failed'].includes(st.status)){setErr('Payment cancelled. No ticket was generated.');setBusy(false);setCancel(true);return}}throw Error('Payment is still pending. Check M-Pesa and try again.')}catch(e){setErr(e instanceof Error?e.message:'Payment could not be completed.');setBusy(false);setCancel(true)}finally{setBusy(false)}}
return <><header><a className="brand" href="#home"><img src={LOGO}/><span>DENNO B <b>STUDIO LAUNCH</b></span></a><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{[['home','Home'],['about','About'],['contact','Contact'],['location','Location'],['tickets','Tickets']].map(x=><a className={page===x[0]?'active':''} href={'#'+x[0]} key={x[0]}>{x[1]}</a>)}</nav></header><main>
{page==='home'&&<><section className="hero"><div><p className="eyebrow">THE OFFICIAL LAUNCH</p><h1>A new chapter<br/><em>begins here.</em></h1><p className="lead">Join us for the DENNO B STUDIO LAUNCH — an afternoon built around people, purpose and a new beginning.</p><a className="btn gold" href="#tickets">Get your ticket <ArrowRight size={16}/></a><div className="facts"><span><CalendarDays/>6 December 2026</span><span><Clock3/>12 PM — 6 PM</span><span><MapPin/>Nairobi Chokaa Stage</span></div></div><div className="heroimg"><img src={PHOTO}/></div></section><section className="section"><p className="eyebrow">CHOOSE YOUR ACCESS</p><h2>Tickets for the launch.</h2><Cards choose={setOpen}/></section></>}
{page==='tickets'&&<section className="section"><p className="eyebrow">TICKETS</p><h1>Reserve your place.</h1><Cards choose={setOpen}/></section>}
{page==='about'&&<section className="section"><p className="eyebrow">ABOUT DENNO B</p><h1>A leader who listens.<br/>A servant who acts.</h1><div className="about"><img src={PHOTO}/><div><h2>People first.</h2><p>Denno B stands for leadership that listens before it speaks, and service that acts when people need it.</p><p>Serve with humility, dedication and honesty, with accountability, respect and strong values.</p></div></div></section>}
{page==='contact'&&<section className="section"><p className="eyebrow">CONTACT</p><h1>We are here to help.</h1><div className="cards"><article><Phone/><h2>WhatsApp support</h2><p>0742197572</p><a className="btn" href={wa('0742197572')}>Open WhatsApp</a></article><article><Phone/><h2>Developer</h2><p>Felix Nyabuto · 0716625790</p><a className="btn" href={wa('0716625790')}>WhatsApp</a></article></div></section>}
{page==='location'&&<section className="section"><p className="eyebrow">LOCATION</p><h1>Nairobi Chokaa Stage.</h1><div className="location"><MapPin/><h2>Nairobi Chokaa Stage</h2><p>6 December 2026 · 12 PM — 6 PM</p><a className="btn gold" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Nairobi+Chokaa+Stage">Open in Maps</a></div></section>}
{page==='ticket'&&(booking?<section className="section ticket"><p className="eyebrow">YOUR DIGITAL TICKET</p><h1>You’re on the list.</h1>{booking.tickets.map((t,i)=><article className="ticketcard" key={t.ticket_number}><div><p className="eyebrow">ADMIT ONE · {booking.ticketName.toUpperCase()} · {i+1} OF {booking.quantity}</p><h2>{booking.name}</h2><p>{booking.email}</p><hr/><b>06 DEC 2026 · 12 PM — 6 PM</b><p>NAIROBI CHOKAA STAGE</p><b>{t.ticket_number}</b></div><div><QRCodeSVG value={JSON.stringify({ticket:t.ticket_number,event:'DENNO B STUDIO LAUNCH',date:'6 December 2026',venue:'Nairobi Chokaa Stage',holder:booking.name,tier:booking.ticketName,qr_token:t.qr_token})} size={190} bgColor="#fff" fgColor="#000"/><small>SCAN AT ENTRY</small></div></article>)}<button className="btn gold" onClick={()=>print()}>Print / Save Ticket</button></section>:<section className="section empty"><Ticket/><h2>No ticket found.</h2><a className="btn gold" href="#tickets">View tickets</a></section>)}
</main>{page==='home'&&<footer>© 2026 DENNO B STUDIO LAUNCH <a href={wa('0716625790')}>Developed by Felix Nyabuto · 0716625790</a></footer>}
{open&&<div className="backdrop"><div className="modal"><button className="close" onClick={()=>!busy&&setOpen(null)}><X/></button><p className="eyebrow">STEP 1 OF 2 · {open[2].toUpperCase()}</p><h2>Your details.</h2><p className="modal-copy">Enter the attendee details, choose the number of tickets, then continue to the M-Pesa payment step.</p><div className="form-grid"><input placeholder="Full name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Phone" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><input className="full" placeholder="Gmail / Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></div><select value={qty} onChange={e=>setQty(Math.max(1,Math.min(20,Number(e.target.value))))}>{Array.from({length:20},(_,i)=><option key={i} value={i+1}>{i+1} ticket{i?'s':''}</option>)}</select><div className="summary"><span>{qty} × {open[2]}</span><b>KES {(open[3]*qty).toLocaleString()}</b></div>{err&&<p className="error">{err}</p>}<button className="btn gold full" disabled={busy} onClick={pay}>{busy?'Sending M-Pesa prompt…':'Send M-Pesa prompt'} <ArrowRight/></button></div></div>}{busy&&<div className="loading"><div><div className="ring">DB</div><p className="eyebrow">DENNO B STUDIO LAUNCH</p><h2>Payment request</h2><p>Complete the M-Pesa request on your phone. Waiting for confirmation.</p><div className="bar"/></div></div>}{cancel&&<div className="notice-backdrop"><div className="notice-modal" role="alertdialog" aria-modal="true"><div className="notice-mark"><X/></div><p className="eyebrow">PAYMENT STATUS</p><h2>Payment cancelled.</h2><p>Your M-Pesa payment was not completed, so no ticket was generated.</p><button className="btn gold full" onClick={()=>{setCancel(false);setOpen(null);setErr('');setBusy(false);setQty(1);setF({name:'',phone:'',email:''})}}>Okay</button></div></div>}</>}
function Cards({choose}:{choose:(x:typeof types[number])=>void}){return <div className="cards">{types.map((t,i)=><article className={i===1?'featured':''} key={t[0]}><p className="eyebrow">{t[2]}</p><strong>KES {t[3].toLocaleString()}</strong><p>{i===0?'Standard entry for the Studio Launch.':i===1?'Premium access for guests who want more.':'The highest access tier for the launch.'}</p><button className="btn" onClick={()=>choose(t)}>Select ticket <ArrowRight size={15}/></button></article>)}</div>}
export default App;
