import { useEffect, useMemo, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { ArrowRight, CalendarDays, Check, Clock3, MapPin, Menu, Phone, ShieldCheck, Ticket, X } from 'lucide-react';

const LOGO_URL='https://hpgujfzzallqfhiufuhn.supabase.co/storage/v1/object/public/dennob%20b%20photos/WhatsApp%20Image%202026-10-07%20at%209.41.16%20PM.jpeg';
const STUDIO_URL='https://hpgujfzzallqfhiufuhn.supabase.co/storage/v1/object/public/dennob%20b%20photos/WhatsApp%20Image%202026-10-07%20at%201.19.58%20PM.jpeg';
const SUPPORT='0742197572';
const DEVELOPER='0716625790';
const tickets=[{id:'regular',name:'Regular',price:500,description:'Standard entry for the Studio Launch.'},{id:'vip',name:'VIP',price:1500,description:'Premium access for guests who want more.'},{id:'vvip',name:'VVIP',price:2000,description:'The highest access tier for the launch.'}];
type Booking={ticketId:string;ticketName:string;price:number;name:string;phone:string;email:string;ticketNumber:string;issuedAt:string};
const pageFromHash=()=>{const value=window.location.hash.replace('#','');return ['home','about','contact','location','tickets','ticket'].includes(value)?value:'home';};

function App(){
 const [page,setPage]=useState(pageFromHash()),[mobileOpen,setMobileOpen]=useState(false),[selected,setSelected]=useState<(typeof tickets)[number]|null>(null),[step,setStep]=useState<'details'|'payment'|'ticket'>('details'),[form,setForm]=useState({name:'',phone:'',email:'',payment:'M-Pesa'}),[errors,setErrors]=useState<Record<string,string>>({});
 const [booking,setBooking]=useState<Booking|null>(()=>{try{const saved=localStorage.getItem('denno-b-studio-ticket');return saved?JSON.parse(saved):null}catch{return null}});
 useEffect(()=>{const onHash=()=>{setPage(pageFromHash());setMobileOpen(false);window.scrollTo({top:0,behavior:'smooth'})};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);
 const openBooking=(ticket:(typeof tickets)[number])=>{setSelected(ticket);setStep('details');setErrors({});setForm({name:'',phone:'',email:'',payment:'M-Pesa'})};
 const validate=()=>{const next:Record<string,string>={};if(!form.name.trim())next.name='Enter your full name.';if(!form.phone.trim()||!/^[0-9+ ]{9,15}$/.test(form.phone.trim()))next.phone='Enter a valid phone number.';if(!form.email.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim()))next.email='Enter a valid email address.';setErrors(next);return Object.keys(next).length===0};
 const createTicket=()=>{if(!selected)return;const issued:Booking={ticketId:selected.id,ticketName:selected.name,price:selected.price,name:form.name.trim(),phone:form.phone.trim(),email:form.email.trim(),ticketNumber:'DBS-'+Math.random().toString(36).slice(2,8).toUpperCase()+'-'+Date.now().toString().slice(-4),issuedAt:new Date().toISOString()};localStorage.setItem('denno-b-studio-ticket',JSON.stringify(issued));setBooking(issued);setStep('ticket');setSelected(null);window.location.hash='ticket'};
 const qrValue=useMemo(()=>booking?JSON.stringify({ticket:booking.ticketNumber,event:'DENNO B STUDIO LAUNCH',date:'6 December 2026',venue:'Nairobi Chokaa Stage',holder:booking.name,tier:booking.ticketName}):'', [booking]);
 return <div className="site-shell">
  <header className="nav-wrap"><div className="nav"><a href="#home" className="brand"><img src={LOGO_URL} alt="Denno B Studio Launch logo"/><span>DENNO B <b>STUDIO LAUNCH</b></span></a><button className="mobile-toggle" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Open navigation">{mobileOpen?<X size={22}/>:<Menu size={22}/>}</button><nav className={mobileOpen?'nav-links open':'nav-links'}><a className={page==='home'?'active':''} href="#home">Home</a><a className={page==='about'?'active':''} href="#about">About</a><a className={page==='contact'?'active':''} href="#contact">Contact</a><a className={page==='location'?'active':''} href="#location">Location</a><a className="nav-ticket" href="#tickets">Tickets</a></nav></div></header>
  <main>
   {page==='home'&&<><section className="hero"><div className="hero-copy"><p className="eyebrow">THE OFFICIAL LAUNCH</p><h1>A new chapter<br/><em>begins here.</em></h1><p className="lead">Join us for the DENNO B STUDIO LAUNCH — an afternoon built around people, purpose and a new beginning.</p><div className="hero-actions"><a className="button gold" href="#tickets">Get your ticket <ArrowRight size={17}/></a><a className="text-link" href="#about">Discover the story</a></div><div className="event-strip"><div><CalendarDays size={18}/><span><b>6 December 2026</b><small>Launch date</small></span></div><div><Clock3 size={18}/><span><b>12:00 PM — 6:00 PM</b><small>Event time</small></span></div><div><MapPin size={18}/><span><b>Nairobi Chokaa Stage</b><small>Event location</small></span></div></div></div><div className="hero-image"><img src={STUDIO_URL} alt="Denno B Studio"/><div className="image-caption"><span>DENNO B</span><small>STUDIO LAUNCH · 2026</small></div></div></section><section className="ticket-preview section"><div className="section-head"><div><p className="eyebrow">CHOOSE YOUR ACCESS</p><h2>Tickets for the launch.</h2></div><p>Every ticket gives you a place in the room for an important new beginning.</p></div><TicketCards onSelect={openBooking}/></section></>}
   {page==='tickets'&&<section className="page-section tickets-page"><PageIntro eyebrow="TICKETS" title="Reserve your place." text="Select your access level, enter your details and complete the payment step to receive your digital ticket with QR code."/><TicketCards onSelect={openBooking}/>{booking&&<div className="existing-ticket"><ShieldCheck size={20}/><span>You already have a ticket on this device.</span><a href="#ticket">View ticket</a></div>}</section>}
   {page==='about'&&<section className="page-section"><PageIntro eyebrow="ABOUT DENNO B" title="A leader who listens. A servant who acts." text="The Studio Launch is about more than an opening. It is about people, service, responsibility and strong values."/><div className="about-grid"><div className="about-image"><img src={STUDIO_URL} alt="Denno B Studio"/></div><div className="manifesto"><p className="eyebrow">THE PURPOSE</p><h3 className="about-purpose">Leadership is service.</h3><p>Denno B is about a people-first approach: listening to people, acting with purpose and showing up with humility, dedication, honesty and strong values.</p><p className="eyebrow">WHAT REALLY IS HAPPENING</p><h2>People first.</h2><p>Denno B stands for leadership that listens before it speaks, and service that acts when people need it. The objective is simple: put people first and serve with humility, dedication and honesty.</p><p>Strong values are not a slogan. They are the standard for how leadership should be carried — with accountability, respect and a commitment to do the work.</p><div className="values"><span>People first</span><span>Humility</span><span>Dedication</span><span>Honesty</span><span>Leadership</span><span>Strong values</span></div></div></div></section>}
   {page==='contact'&&<section className="page-section contact-page"><PageIntro eyebrow="CONTACT" title="We are here to help." text="For ticket support, directions, payment questions or any launch enquiries, reach the support team directly."/><div className="contact-grid"><ContactCard title="WhatsApp support" text="Message the support team for quick assistance." href={'https://wa.me/254'+SUPPORT.slice(1)} action="Open WhatsApp"/><ContactCard title="Call support" text="Speak directly with the launch support team." href={'tel:'+SUPPORT} action={SUPPORT}/><ContactCard title="Event date" text="6 December 2026 · 12:00 PM — 6:00 PM" href="#location" action="View location"/></div></section>}
   {page==='location'&&<section className="page-section"><PageIntro eyebrow="LOCATION" title="Nairobi Chokaa Stage." text="The DENNO B STUDIO LAUNCH takes place at Nairobi Chokaa Stage on 6 December 2026, from 12:00 PM to 6:00 PM."/><div className="location-card"><div className="location-details"><div className="location-icon"><MapPin size={26}/></div><p className="eyebrow">EVENT VENUE</p><h2>Nairobi Chokaa Stage</h2><p>Plan your journey ahead of time and arrive early for a smooth check-in.</p><a className="button charcoal" href="https://www.google.com/maps/search/?api=1&query=Nairobi+Chokaa+Stage" target="_blank" rel="noreferrer">Open in Maps <ArrowRight size={17}/></a></div><div className="map-placeholder"><MapPin size={40}/><span>NAIROBI<br/>CHOKAA STAGE</span></div></div></section>}
   {page==='ticket'&&booking&&<section className="page-section ticket-page"><PageIntro eyebrow="YOUR DIGITAL TICKET" title="You’re on the list." text="Keep this ticket safe and present the QR code at the event entrance."/><div className="ticket-card"><div className="ticket-main"><div className="ticket-top"><span>DENNO B</span><span>STUDIO LAUNCH</span></div><div className="ticket-title"><p className="eyebrow">ADMIT ONE · {booking.ticketName.toUpperCase()}</p><h2>{booking.name}</h2><p>{booking.email}</p></div><div className="ticket-meta"><div><small>DATE</small><b>06 DEC 2026</b></div><div><small>TIME</small><b>12 PM — 6 PM</b></div><div><small>VENUE</small><b>NAIROBI CHOKAA STAGE</b></div><div><small>TICKET</small><b>{booking.ticketNumber}</b></div></div></div><div className="ticket-qr"><QRCodeSVG value={qrValue} size={190} bgColor="#FFFFFF" fgColor="#000000" level="M"/><small>SCAN AT ENTRY</small></div></div><div className="ticket-actions"><button className="button gold" onClick={()=>window.print()}>Print / Save Ticket</button><a className="button outline" href="#tickets">Book another</a></div></section>}
   {page==='ticket'&&!booking&&<section className="page-section empty-ticket"><Ticket size={30}/><h2>No ticket found.</h2><p>Choose a ticket to start your booking.</p><a className="button gold" href="#tickets">View tickets</a></section>}
  </main>
  {page==='home'&&<footer><div className="footer-bottom"><span>© 2026 DENNO B STUDIO LAUNCH</span><a href={'https://wa.me/254'+DEVELOPER.slice(1)} target="_blank" rel="noreferrer">Developed by Felix Nyabuto · {DEVELOPER}</a></div></footer>}
  {selected&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="booking-modal" role="dialog" aria-modal="true" aria-label="Book ticket"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close"><X size={20}/></button>{step==='details'&&<><p className="eyebrow">STEP 1 OF 2</p><h2>Your details.</h2><p className="modal-copy">Booking <b>{selected.name}</b> · KES {selected.price.toLocaleString()}</p><div className="form-grid"><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your full name"/>{errors.name&&<small className="error">{errors.name}</small>}</label><label>Phone number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="07XX XXX XXX"/>{errors.phone&&<small className="error">{errors.phone}</small>}</label><label className="full">Gmail / Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@gmail.com"/>{errors.email&&<small className="error">{errors.email}</small>}</label></div><button className="button gold full-button" onClick={()=>validate()&&setStep('payment')}>Continue to payment <ArrowRight size={17}/></button></>}{step==='payment'&&<><p className="eyebrow">STEP 2 OF 2</p><h2>Complete payment.</h2><div className="order-summary"><span>{selected.name} ticket</span><strong>KES {selected.price.toLocaleString()}</strong></div><div className="payment-note"><ShieldCheck size={19}/><div><b>Payment gateway ready</b><p>The live M-Pesa/card connection needs the payment provider credentials. For now, this button completes the booking demonstration without charging your phone or card.</p></div></div><label className="payment-select">Payment method<select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})}><option>M-Pesa</option><option>Card</option></select></label><button className="button gold full-button" onClick={createTicket}>Confirm payment & issue ticket <Check size={17}/></button><button className="back-link" onClick={()=>setStep('details')}>Back to details</button></>}</div></div>}
 </div>;
}
function TicketCards({onSelect}:{onSelect:(ticket:(typeof tickets)[number])=>void}){return <div className="ticket-grid">{tickets.map(ticket=><article className={ticket.id==='vip'?'ticket-option featured':'ticket-option'} key={ticket.id}>{ticket.id==='vip'&&<span className="popular">MOST POPULAR</span>}<p className="ticket-tier">{ticket.name}</p><div className="price"><small>KES</small><strong>{ticket.price.toLocaleString()}</strong></div><p>{ticket.description}</p><button className="button outline" onClick={()=>onSelect(ticket)}>Select {ticket.name} <ArrowRight size={16}/></button></article>)}</div>}
function PageIntro({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>}
function ContactCard({title,text,href,action}:{title:string;text:string;href:string;action:string}){return <article className="contact-card"><div className="contact-icon"><Phone size={20}/></div><h2>{title}</h2><p>{text}</p><a className="text-link" href={href} target={href.startsWith('http')?'_blank':undefined} rel={href.startsWith('http')?'noreferrer':undefined}>{action} <ArrowRight size={16}/></a></article>}
export default App;
